/* ============================================================
   CFB 27 PLAY CALLER — CONCEPT LIBRARY
   Every entry is a real CFB 27 / football concept tagged with:
     n    name
     t    type: run | qb | rpo | quick | mid | shot | pa | screen | trick
     fam  formation families it can be run from
     b    what it BEATS (matched against the opponent's defensive DNA)
     s    situations it belongs in
     st   offensive styles that carry it ("*" = every playbook)
     look what the play-caller is reading
   ============================================================ */
(function (global) {
  "use strict";

  var SITS = ["open", "1st10", "2sh", "2md", "2lg", "3sh", "3md", "3lg", "4th",
    "rz20", "rz10", "gl", "backed", "2min", "4min", "shot", "screen", "trick", "2pt"];

  function p(n, t, fam, b, s, st, look) {
    return { n: n, t: t, fam: fam, b: b, s: s, st: st || "*", look: look || "" };
  }

  var ALL_GUN = ["gun", "pistol", "single", "iform", "uc"];

  var PLAYS = [
    /* ---------------- INSIDE / ZONE RUN ---------------- */
    p("Inside Zone", "run", ALL_GUN, ["light-box", "2-high", "3-high", "six-db"],
      ["open", "1st10", "2sh", "2md", "3sh", "4th", "rz20", "4min"], "*",
      "Count the box. Six or fewer defenders, give it and let the back cut off the first-level double."),
    p("Inside Zone Split", "run", ["gun", "pistol", "single"], ["blitz", "light-box", "tite"],
      ["1st10", "2md", "4min", "rz20"], "*",
      "H-back cuts off the backside edge — kills the free rusher on a slanting front."),
    p("Outside Zone", "run", ALL_GUN, ["light-box", "tite", "heavy-box"],
      ["open", "1st10", "2md", "rz20", "4min"], "*",
      "Get the front moving laterally. Bang it if the DE widens, bounce if the corner is soft."),
    p("Stretch", "run", ["gun", "pistol", "single", "iform"], ["tite", "light-box", "2-high"],
      ["1st10", "2md", "4min"], "*",
      "Reach the 3-tech. Against a tite front this is the escape hatch to the perimeter."),
    p("Duo", "run", ["gun", "single", "iform", "uc"], ["light-box", "1-high", "six-db"],
      ["1st10", "2sh", "3sh", "4min", "rz20", "rz10"], "*",
      "Double team to the linebacker. Pure downhill answer to a light box."),
    p("Iso Lead", "run", ["iform", "uc", "gl"], ["light-box", "six-db", "2-high"],
      ["1st10", "2sh", "3sh", "gl", "4min", "4th"], "*",
      "Fullback on the plugger. If they are in nickel or dime, this is free yardage."),
    p("Zone Dive", "run", ["gun", "pistol", "option", "flex"], ["light-box", "six-db"],
      ["1st10", "2sh", "3sh", "4min", "gl"], "*", "Fast-hitting A-gap dive off the mesh point."),

    /* ---------------- GAP / POWER RUN ---------------- */
    p("Power O", "run", ["gun", "pistol", "iform", "uc", "gl", "heavy"], ["light-box", "tite", "2-high"],
      ["1st10", "2sh", "2md", "3sh", "gl", "rz10", "4min", "4th"], "*",
      "Down-block, kick the edge, pull the guard through. Physical answer to a light box."),
    p("Counter Trey", "run", ["gun", "pistol", "iform", "uc", "heavy"], ["blitz", "light-box", "man"],
      ["1st10", "2md", "rz20", "4min"], "*",
      "Punish over-pursuit. The better their linebackers flow, the better this looks."),
    p("GT Counter", "run", ["gun", "pistol", "single", "iform"], ["tite", "blitz", "heavy-box"],
      ["1st10", "2md", "3sh", "rz20"], "*", "Guard-tackle pull away from the tite front's strength."),
    p("Trap", "run", ["gun", "single", "iform", "uc"], ["tite", "blitz", "heavy-box"],
      ["1st10", "2sh", "2md", "4min"], "*", "Let the penetrating 3-tech come — trap him and run through the crease."),
    p("Wham", "run", ["gun", "pistol", "single"], ["tite", "heavy-box", "blitz"],
      ["1st10", "2md", "rz20"], "*", "H-back whams the nose. Best call in the book against a 0-technique."),
    p("Dart", "run", ["gun", "pistol", "single"], ["tite", "light-box"],
      ["1st10", "2md", "4min"], "*", "Tackle pulls, back runs downhill behind him."),
    p("Pin & Pull Sweep", "run", ["gun", "pistol", "single", "iform"], ["heavy-box", "tite", "1-high"],
      ["1st10", "2md", "rz20", "4min"], "*", "Pin the interior, pull to the edge. Gets you outside a loaded box."),
    p("Toss Crack", "run", ["gun", "single", "iform", "uc"], ["heavy-box", "press", "1-high"],
      ["1st10", "2md", "rz20"], "*", "Crack the safety, kick the corner, get the back on the numbers fast."),
    p("Jet Sweep", "run", ["gun", "pistol", "single", "trips", "bunch"], ["heavy-box", "blitz", "1-high"],
      ["open", "1st10", "2sh", "2md", "rz20"], "*", "Attack the overhang's leverage. Tempo call to test their edge discipline."),
    p("Crack Toss", "run", ["gl", "heavy", "uc", "iform"], ["heavy-box", "press"],
      ["rz10", "gl", "4th", "2pt"], "*", "Goal-line perimeter run — get the corner blocked and turn it up."),

    /* ---------------- OPTION RUN ---------------- */
    p("Triple Option (Veer)", "run", ["option", "flex", "uc"], ["heavy-box", "man", "blitz", "1-high"],
      ["open", "1st10", "2sh", "2md", "3sh", "4min", "gl", "4th"], ["Option", "Spread Option", "Veer & Shoot"],
      "Read the first two defenders outside the tackle. Make both of them wrong."),
    p("Midline Option", "run", ["option", "flex", "uc", "pistol"], ["tite", "heavy-box", "blitz"],
      ["1st10", "2sh", "3sh", "4min", "gl"], ["Option", "Spread Option"],
      "Read the 3-tech. The harder they pinch inside, the more this hits."),
    p("Speed Option", "run", ["gun", "pistol", "option", "flex", "uc"], ["heavy-box", "man", "press"],
      ["1st10", "2md", "3sh", "rz20", "gl"], ["Option", "Spread Option", "Pistol", "Power Spread", "Go Go", "Veer & Shoot"],
      "Pitch key is the edge. Man coverage means nobody is watching the QB."),
    p("Load Option", "run", ["option", "flex", "uc", "pistol"], ["blitz", "heavy-box"],
      ["1st10", "2md", "3sh", "4min"], ["Option", "Spread Option"], "Load the edge defender and read the next man out."),
    p("Rocket Toss", "run", ["option", "flex", "gun", "uc"], ["heavy-box", "1-high", "tite"],
      ["1st10", "2md", "rz20"], ["Option", "Spread Option", "Veer & Shoot", "Go Go"],
      "Motion back gets width in a hurry — outflank the front."),
    p("Zone Read", "run", ["gun", "pistol", "option", "flex"], ["blitz", "heavy-box", "man"],
      ["open", "1st10", "2sh", "2md", "3sh", "4min", "rz20"], ["Spread", "Spread Option", "Power Spread", "Go Go", "Veer & Shoot", "Pistol", "Multiple", "Option"],
      "Read the backside end. If he chases, pull it and go."),
    p("Power Read (Bash)", "run", ["gun", "pistol", "option"], ["heavy-box", "man", "blitz"],
      ["1st10", "2md", "3sh", "rz20", "rz10"], ["Spread Option", "Power Spread", "Go Go", "Multiple", "Veer & Shoot"],
      "Back away, QB keeps on the down block — flips the run strength after the snap."),
    p("Sweep Read", "run", ["gun", "pistol", "trips", "bunch"], ["heavy-box", "1-high"],
      ["1st10", "2md", "rz20"], ["Spread Option", "Power Spread", "Go Go", "Spread", "Veer & Shoot"],
      "Jet sweep with the give read inside. Punishes an over-aggressive edge."),

    /* ---------------- QB RUN ---------------- */
    p("QB Power", "qb", ["gun", "pistol", "option", "wildcat"], ["light-box", "six-db", "2-high"],
      ["1st10", "2sh", "3sh", "rz10", "gl", "4th", "2pt"], ["Spread Option", "Power Spread", "Go Go", "Multiple", "Option", "Pistol"],
      "Extra hat at the point of attack. Dime and nickel personnel cannot hold this up."),
    p("QB Counter", "qb", ["gun", "pistol", "option"], ["light-box", "six-db", "blitz"],
      ["1st10", "2md", "3sh", "rz10", "4th"], ["Spread Option", "Power Spread", "Go Go", "Multiple", "Veer & Shoot"],
      "Two pullers with the QB carrying — best short-yardage call against sub personnel."),
    p("QB Draw", "qb", ["gun", "empty", "spread"], ["blitz", "six-db", "3-high", "2-high"],
      ["2lg", "3md", "3lg", "2min"], "*", "Let them rush upfield out of a light box and run through the vacated middle."),
    p("Designed QB Keep", "qb", ["gun", "pistol", "option", "flex"], ["man", "blitz", "heavy-box"],
      ["1st10", "2md", "3sh", "rz10", "gl"], ["Spread Option", "Option", "Power Spread", "Go Go"],
      "Nobody has the quarterback in man coverage."),
    p("QB Sneak", "qb", ["gl", "heavy", "uc", "gun", "single"], ["light-box", "six-db", "heavy-box"],
      ["2sh", "3sh", "4th", "gl", "2pt"], "*", "Snap it and fall forward. Highest-percentage yard in football."),
    p("RB Draw", "run", ["gun", "spread", "single", "doubles"], ["blitz", "2-high", "3-high"],
      ["2lg", "3md", "3lg", "2min"], "*", "Sell the drop, hand it into the vacated box."),

    /* ---------------- RPO ---------------- */
    p("RPO Glance", "rpo", ["gun", "pistol", "trips", "spread", "doubles"], ["1-high", "man", "blitz", "light-box"],
      ["open", "1st10", "2md", "3sh", "rz20"], ["Spread", "Spread Option", "Power Spread", "Go Go", "Veer & Shoot", "Multiple", "Pistol"],
      "Inside zone with the glance post tagged. Single-high safety gets outnumbered."),
    p("RPO Bubble", "rpo", ["gun", "trips", "bunch", "spread", "pistol"], ["heavy-box", "blitz", "tite"],
      ["open", "1st10", "2sh", "2md", "3sh"], ["Spread", "Spread Option", "Power Spread", "Go Go", "Air Raid", "Veer & Shoot", "Run & Shoot", "Multiple"],
      "Box count decides it — loaded box, throw the bubble and let the slot run."),
    p("RPO Arrow", "rpo", ["gun", "trips", "spread", "doubles"], ["heavy-box", "zone", "tite"],
      ["1st10", "2sh", "2md", "3sh"], ["Spread", "Power Spread", "Go Go", "Spread Option", "Multiple", "Veer & Shoot"],
      "Read the apex defender. He fits the run, the arrow is open behind him."),
    p("RPO Pop Pass", "rpo", ["gun", "pistol", "te", "tight", "option", "flex"], ["light-box", "1-high", "blitz"],
      ["1st10", "2md", "rz20", "rz10"], ["Spread Option", "Power Spread", "Pistol", "Option", "Multiple", "Go Go"],
      "Linebackers step up on the run action — pop it over their heads to the seam."),
    p("RPO Stick", "rpo", ["gun", "trips", "bunch", "spread"], ["zone", "light-box", "match"],
      ["1st10", "2sh", "3sh", "2md"], ["Spread", "Air Raid", "Run & Shoot", "Power Spread", "Multiple", "Go Go"],
      "Run read first, stick-flat if the box is loaded."),
    p("RPO Fade Alert", "rpo", ["gun", "trips", "spread", "doubles"], ["press", "man", "1-high"],
      ["1st10", "2md", "rz10", "gl", "2pt"], ["Spread", "Spread Option", "Power Spread", "Veer & Shoot", "Multiple", "Air Raid"],
      "Press with no safety help outside — take the free fade off run action."),

    /* ---------------- QUICK GAME ---------------- */
    p("Stick", "quick", ["gun", "trips", "bunch", "spread", "single", "empty"], ["zone", "blitz", "light-box", "match"],
      ["open", "2sh", "3sh", "3md", "2min", "rz20"], "*", "Stick-flat-hitch triangle. Zone defenders can only cover two of three."),
    p("Snag", "quick", ["gun", "trips", "bunch", "empty", "single"], ["zone", "man", "blitz"],
      ["open", "2md", "3sh", "3md", "rz20", "2min"], "*", "Spot-corner-flat triangle — the universal answer, man or zone."),
    p("Spot", "quick", ["gun", "bunch", "trips", "empty"], ["man", "blitz", "press"],
      ["open", "2sh", "3sh", "3md", "rz10", "gl", "2pt"], "*", "Natural rub inside the bunch. Man coverage gets legally screened."),
    p("Double Slants", "quick", ["gun", "doubles", "spread", "empty", "single"], ["man", "press", "blitz"],
      ["open", "1st10", "2sh", "3sh", "2min", "backed"], "*", "Beat press leverage inside. Fastest ball out of the quarterback's hand."),
    p("Slant-Flat", "quick", ["gun", "doubles", "trips", "spread", "single"], ["zone", "press", "blitz"],
      ["open", "1st10", "2sh", "3sh", "backed", "2min"], "*", "Flat stretches the corner, slant sits behind him."),
    p("Whip / Pivot", "quick", ["gun", "bunch", "trips", "spread", "empty"], ["man", "press", "match"],
      ["2sh", "2md", "3sh", "3md", "rz10", "gl"], "*", "Break back against the man defender's momentum."),
    p("All Curls", "quick", ["gun", "doubles", "spread", "empty", "single"], ["zone", "blitz", "2-high"],
      ["2md", "3md", "2min", "backed"], "*", "Five-step curls with an outlet. Take what the zone gives."),
    p("Spacing", "quick", ["gun", "bunch", "trips", "empty", "spread"], ["zone", "blitz", "match"],
      ["2sh", "2md", "3sh", "3md", "2min", "backed", "rz20"], "*", "Flood every zone hole. Great tempo and two-minute call."),
    p("Hank", "quick", ["gun", "doubles", "spread", "single", "empty"], ["blitz", "zone"],
      ["2md", "3md", "backed", "2min"], "*", "Built-in blitz beater — hitches with an inside sit route."),
    p("Curl-Flat", "quick", ["gun", "doubles", "trips", "single", "iform"], ["zone", "2-high", "match"],
      ["1st10", "2md", "3md"], "*", "Stretch the curl-flat defender horizontally."),
    p("Stick Nod", "quick", ["gun", "trips", "bunch", "spread"], ["zone", "match", "blitz"],
      ["2md", "3md", "rz20"], "*", "Sell the stick, break vertical when the hook player jumps it."),
    p("Choice", "quick", ["gun", "empty", "spread", "doubles"], ["man", "press", "match"],
      ["open", "2md", "3md", "3lg", "2min"], ["Run & Shoot", "Air Raid", "Spread", "Veer & Shoot", "Multiple"],
      "Receiver and quarterback read the same leverage — option cut off the defender's hips."),
    p("Y-Iso", "quick", ["gun", "empty", "spread", "doubles", "tight"], ["man", "1-high", "press"],
      ["2md", "3md", "3lg", "rz20"], "*", "Isolate the best matchup and let him work one-on-one."),
    p("Sprint Out Flood", "quick", ["gun", "trips", "bunch", "spread"], ["man", "blitz", "zone"],
      ["2sh", "3sh", "3md", "backed", "2min"], "*", "Move the pocket away from pressure and flood one side."),
    p("Fade-Out", "quick", ["gun", "doubles", "spread", "trips"], ["press", "2-high", "match"],
      ["3md", "rz10", "gl", "2min", "2pt"], "*", "Back-shoulder fade or the out underneath — pick on the press corner."),
    p("Slot Fade", "quick", ["gun", "trips", "bunch", "spread", "empty"], ["press", "man", "1-high"],
      ["rz10", "gl", "2pt", "4th"], "*", "No safety help over the slot — throw it to the pylon."),

    /* ---------------- MESH / CROSSING ---------------- */
    p("Mesh", "quick", ["gun", "bunch", "trips", "empty", "spread", "doubles"], ["man", "blitz", "press", "1-high"],
      ["open", "1st10", "2md", "3md", "3lg", "rz20", "2min"], "*",
      "Two shallow crossers rub off each other. The single best man beater in the game."),
    p("Mesh Sit", "quick", ["gun", "bunch", "trips", "empty", "spread"], ["zone", "blitz", "match"],
      ["2md", "3md", "3lg", "2min", "backed"], "*", "Same mesh, crossers sit down in the zone windows."),
    p("Mesh Spot", "mid", ["gun", "bunch", "doubles", "trips", "tight"], ["man", "zone", "blitz"],
      ["open", "1st10", "2md", "3md", "rz20"], "*", "Mesh with a spot-corner behind it — covers man and zone in one call."),
    p("Mesh Deep Over", "mid", ["gun", "bunch", "doubles", "trips", "tight"], ["man", "1-high", "blitz"],
      ["1st10", "2md", "2lg", "3md", "3lg", "shot"], "*",
      "Mesh underneath holds the linebackers, the deep over runs behind them."),
    p("Shallow Cross", "mid", ["gun", "trips", "doubles", "empty", "spread"], ["man", "1-high", "blitz"],
      ["2md", "2lg", "3md", "3lg"], "*", "Shallow with the dig behind it — classic man-coverage two-level answer."),
    p("Drive", "mid", ["gun", "doubles", "trips", "single", "tight"], ["man", "blitz", "1-high"],
      ["1st10", "2md", "3md", "rz20"], "*", "Drive route under, dig over the top. Beats matched man."),
    p("Y-Cross", "mid", ["gun", "trips", "doubles", "single", "tight", "iform"], ["man", "zone", "1-high"],
      ["1st10", "2md", "2lg", "3md", "shot"], "*", "Deep crosser off the play-side hash with a check-down built in."),
    p("Follow / Pin", "mid", ["gun", "bunch", "trips", "tight"], ["man", "press"],
      ["2md", "3md", "rz20", "rz10"], "*", "Stacked crossers — man defenders run into each other."),
    p("Trail", "mid", ["gun", "doubles", "trips", "single"], ["man", "blitz", "match"],
      ["2md", "3md", "3lg"], "*", "Deep-in with the trail route underneath for the scramble outlet."),

    /* ---------------- INTERMEDIATE / ZONE BEATERS ---------------- */
    p("Levels", "mid", ["gun", "doubles", "trips", "single", "iform", "tight"], ["zone", "match", "2-high"],
      ["1st10", "2md", "3md", "rz20"], "*", "High-low the hook defender with two in-cuts at different depths."),
    p("Dagger", "mid", ["gun", "doubles", "trips", "spread", "empty"], ["2-high", "match", "zone"],
      ["1st10", "2lg", "3md", "3lg", "shot"], "*", "Seam clears the safety, dig sits in the vacated middle. The quarters killer."),
    p("Post-Dig (Mills)", "mid", ["gun", "doubles", "trips", "single", "iform"], ["2-high", "match", "1-high"],
      ["1st10", "2lg", "3md", "3lg", "shot"], "*", "Dig pulls the safety down, post runs behind him."),
    p("Bang 8", "mid", ["gun", "doubles", "spread", "single", "iform"], ["2-high", "zone"],
      ["1st10", "2md", "2lg", "shot"], "*", "Skinny post between the safeties in a two-high shell."),
    p("Sail / Flood", "mid", ["gun", "trips", "bunch", "single", "iform", "uc"], ["zone", "3-high", "2-high"],
      ["2md", "2lg", "3md", "3lg", "backed"], "*", "Three-level flood — the zone can only cover two of the three."),
    p("Smash", "mid", ["gun", "doubles", "trips", "spread", "single"], ["2-high", "match", "3-high", "press"],
      ["1st10", "2md", "3md", "rz20", "rz10"], "*", "Hitch-corner combination. High-low the corner in quarters."),
    p("Corner-Flat", "mid", ["gun", "doubles", "trips", "bunch", "single"], ["2-high", "zone", "match"],
      ["2md", "3md", "rz20", "rz10"], "*", "Flat holds the corner, the corner route works over him."),
    p("Deep Over", "mid", ["gun", "doubles", "trips", "tight", "single"], ["man", "1-high", "blitz"],
      ["1st10", "2lg", "3md", "3lg", "shot"], "*", "Backside over route across the field — man coverage cannot run with it."),
    p("Seam Bender", "mid", ["gun", "trips", "spread", "empty", "doubles"], ["3-high", "2-high", "zone"],
      ["1st10", "2md", "2lg", "3md", "shot"], "*", "Bend the seam away from the middle-third safety."),
    p("Divide", "mid", ["gun", "empty", "spread", "trips", "doubles"], ["1-high", "man", "zone"],
      ["1st10", "2md", "2lg", "3md", "shot"], "*", "Two seams divide the single-high safety — he can only pick one."),
    p("Hoss Y Juke", "mid", ["gun", "doubles", "spread", "empty", "single"], ["blitz", "man", "1-high"],
      ["2md", "3md", "3lg", "2min", "backed"], "*", "Hitch-seam with a juke route underneath. Built for Cover 0."),
    p("Curl-Wheel", "mid", ["gun", "trips", "bunch", "doubles"], ["man", "match", "press"],
      ["2md", "2lg", "3md", "shot"], "*", "Wheel off the curl — man defenders get stacked up underneath."),
    p("Sideline Comeback", "mid", ["gun", "doubles", "spread", "trips", "empty"], ["match", "press", "2-high"],
      ["2lg", "3md", "3lg", "2min"], "*", "Comeback on the numbers — the two-minute yardage-and-clock call."),
    p("Out & Up", "mid", ["gun", "doubles", "trips", "spread"], ["match", "press", "zone"],
      ["2lg", "3lg", "shot", "2min"], "*", "After you have hit the out twice, break it vertical."),

    /* ---------------- SHOTS ---------------- */
    p("Four Verticals", "shot", ["gun", "empty", "spread", "trips", "doubles"], ["1-high", "man", "blitz"],
      ["1st10", "2lg", "3lg", "shot", "2min"], "*", "Four on three against single high. Throw the open seam."),
    p("Post-Wheel", "shot", ["gun", "trips", "bunch", "doubles", "pistol"], ["man", "press", "1-high"],
      ["1st10", "2lg", "shot", "rz20"], "*", "Post clears, wheel runs up the sideline — death to man coverage."),
    p("Double Post", "shot", ["gun", "doubles", "trips", "spread"], ["1-high", "man", "zone"],
      ["1st10", "2lg", "shot"], "*", "Two posts at different depths bracket the middle-third safety."),
    p("Sluggo Seam", "shot", ["gun", "doubles", "spread", "trips", "empty"], ["man", "press", "match"],
      ["1st10", "2lg", "3lg", "shot"], "*", "Slant-and-go after you have thrown the slant. Aggressive corners bite."),
    p("Deep Corner Strike", "shot", ["gun", "doubles", "trips", "bunch"], ["2-high", "match", "press"],
      ["1st10", "2lg", "shot", "rz20"], "*", "Attack the quarters corner's outside shoulder off a hard stem inside."),
    p("Switch Verts", "shot", ["gun", "spread", "empty", "doubles", "trips"], ["man", "press", "1-high"],
      ["1st10", "2lg", "3lg", "shot"], "*", "Switch release beats press and confuses the man-match rules."),

    /* ---------------- PLAY ACTION ---------------- */
    p("PA Crosser", "pa", ["gun", "pistol", "iform", "single", "uc", "tight"], ["1-high", "heavy-box", "man", "blitz"],
      ["open", "1st10", "2sh", "2md", "shot", "rz20"], "*",
      "Run action sucks the linebackers up, the crosser comes out behind them."),
    p("PA Deep Cross", "pa", ["gun", "pistol", "iform", "single", "uc"], ["1-high", "man", "blitz", "heavy-box"],
      ["1st10", "2sh", "2md", "shot"], "*", "Same-picture run fake, deep crosser over the top. Best shot off a run-heavy script."),
    p("PA Post Shot (Yankee)", "pa", ["gun", "pistol", "iform", "single", "uc"], ["1-high", "blitz", "heavy-box"],
      ["1st10", "2sh", "shot"], "*", "Over and post cross the single-high safety's face — make him wrong."),
    p("PA Boot Wheel", "pa", ["gun", "pistol", "iform", "uc", "tight"], ["zone", "1-high", "blitz"],
      ["1st10", "2sh", "2md", "shot", "rz20"], "*", "Boot away from the run fake — the flow defenders are all gone."),
    p("PA All Curls", "pa", ["gun", "pistol", "single", "iform"], ["zone", "2-high", "heavy-box"],
      ["1st10", "2sh", "2md"], "*", "Freeze the second level, throw the curls behind them."),
    p("PA Y-Cross", "pa", ["gun", "pistol", "single", "iform", "tight", "uc"], ["1-high", "man", "heavy-box"],
      ["1st10", "2sh", "2md", "shot", "rz20"], "*", "Y-cross off the zone fake with the shot built in."),
    p("PA Naked Boot", "pa", ["gun", "pistol", "iform", "uc", "option", "flex"], ["zone", "blitz", "man"],
      ["1st10", "2sh", "rz20", "rz10", "backed"], "*", "Nobody blocks the backside — QB boots out and throws on the run."),
    p("PA Option Shot", "pa", ["option", "flex", "uc", "pistol", "gun"], ["heavy-box", "1-high", "man"],
      ["1st10", "2sh", "shot", "rz20"], ["Option", "Spread Option", "Veer & Shoot", "Pistol"],
      "Show triple option, throw the pitch-and-go over the crashing corner."),

    /* ---------------- SCREENS ---------------- */
    p("RB Swing Screen", "screen", ["gun", "pistol", "spread", "doubles", "trips", "empty"], ["blitz", "man", "heavy-box"],
      ["screen", "1st10", "2md", "3md", "backed", "2min"], "*", "Free yards against pressure — get it outside the rush."),
    p("RB Slip Screen", "screen", ["gun", "pistol", "single", "doubles"], ["blitz", "zone", "man"],
      ["screen", "2lg", "3md", "3lg", "backed"], "*", "Let the rush come, slip the back behind them."),
    p("WR Tunnel Screen", "screen", ["gun", "trips", "bunch", "spread", "doubles"], ["press", "blitz", "heavy-box"],
      ["screen", "1st10", "2md", "3md"], "*", "Press corner runs himself out of the play — tunnel behind the blocks."),
    p("Bubble Screen", "screen", ["gun", "trips", "bunch", "spread", "empty"], ["heavy-box", "zone", "blitz"],
      ["screen", "open", "1st10", "2sh", "2md", "backed"], "*", "Punish the loaded box. Take the free perimeter yardage."),
    p("Jailbreak Screen", "screen", ["gun", "doubles", "spread", "trips"], ["blitz", "zone", "2-high"],
      ["screen", "2md", "3md", "backed"], "*", "All five receivers block — best against a soft, deep-dropping shell."),
    p("TE Middle Screen", "screen", ["gun", "single", "tight", "doubles", "te"], ["blitz", "zone", "man"],
      ["screen", "2lg", "3lg"], "*", "Interior rush lanes clear out — screen right up the middle of the field."),
    p("Double Screen", "screen", ["gun", "trips", "spread", "doubles"], ["blitz", "man", "zone"],
      ["screen", "1st10", "2md", "3md"], "*", "Screen on both sides — throw to whichever one the defense vacates."),

    /* ---------------- TWO-MINUTE / CLOCK ---------------- */
    p("Sideline Out", "quick", ["gun", "doubles", "spread", "empty", "trips"], ["zone", "match", "2-high"],
      ["2min", "3md", "2lg"], "*", "Ball on the sideline, clock stops. Bread and butter of the two-minute drive."),
    p("Seam Sit", "quick", ["gun", "empty", "spread", "trips", "doubles"], ["zone", "match", "3-high"],
      ["2min", "3md", "2lg"], "*", "Seam route sits down in the hole between the hash defenders."),
    p("Dagger Sit", "mid", ["gun", "doubles", "trips", "empty"], ["2-high", "zone", "match"],
      ["2min", "3lg", "2lg"], "*", "Dagger with the dig throttled down in front of the sticks."),
    p("Hail Mary", "shot", ["gun", "empty", "spread"], ["zone", "3-high", "2-high"],
      ["2min"], "*", "Last snap of the half. Four deep, throw it to the back of the end zone."),

    /* ---------------- TRICKS & SPECIALS ---------------- */
    p("Flea Flicker", "trick", ["gun", "pistol", "iform", "single", "uc"], ["1-high", "heavy-box", "zone"],
      ["trick", "shot", "1st10"], "*", "Hand it, get it back, throw the post. Safeties have already triggered."),
    p("Reverse Pass", "trick", ["gun", "trips", "bunch", "single", "iform"], ["blitz", "zone", "1-high"],
      ["trick", "shot"], "*", "Jet reverse into a throw back across the field."),
    p("Double Pass", "trick", ["gun", "doubles", "trips", "spread"], ["press", "man", "zone"],
      ["trick", "shot"], "*", "Throw the screen behind the line, then throw it deep off the bite."),
    p("Philly Special", "trick", ["gl", "heavy", "uc", "single"], ["man", "heavy-box", "press"],
      ["trick", "gl", "2pt", "4th"], "*", "Direct snap, pitch, quarterback releases uncovered into the end zone."),
    p("Fake Jet Screen Pass", "trick", ["gun", "trips", "bunch", "spread"], ["blitz", "press", "zone"],
      ["trick", "screen"], "*", "Show the jet screen, throw the wheel over the defender chasing it."),
    p("Wildcat Direct Snap", "trick", ["wildcat", "gun", "gl", "heavy"], ["light-box", "man", "six-db"],
      ["trick", "gl", "3sh", "4th", "2pt"], "*", "Direct snap to the back with an extra puller. Nobody has the quarterback."),
    p("Swinging Gate", "trick", ["special", "trick"], ["zone", "light-box"],
      ["trick", "2pt", "4th"], "*", "Unbalanced alignment — snap it before they can align to it.")
  ];

  /* motion / shift tags and protections used to dress calls */
  var MOTIONS = ["Z-Motion", "Jet Shift", "Orbit Motion", "Y-Shift Tight", "Tight Bunch Shift",
    "Flip Trips", "Swap Release", "Fake Jet Shift", "Slot Over", "Hard Y-Flex"];
  var PROTECTIONS_DEEP = ["Max Pro (7-man)", "Half-Slide Rt", "Half-Slide Lt", "Slide Lt + RB Kick", "6-Man Fan"];
  var PROTECTIONS_QUICK = ["3-Step", "Quick 3 + Alert", "Sprint Rt", "Sprint Lt", "Empty 5-Man"];

  global.CFB27_PLAYS = { PLAYS: PLAYS, SITS: SITS, MOTIONS: MOTIONS, PROTECTIONS_DEEP: PROTECTIONS_DEEP, PROTECTIONS_QUICK: PROTECTIONS_QUICK };
})(typeof window !== "undefined" ? window : globalThis);
